/* Navigation */
export const NAVIGATION_PUSH = 'NAVIGATION/PUSH'
export const NAVIGATION_REPLACE = 'NAVIGATION/REPLACE'
export const NAVIGATION_GO_BACK = 'NAVIGATION/GO_BACK'
export const NAVIGATION_LOCATION_CHANGE = 'NAVIGATION/LOCATION_CHANGE'

/* User */
export const USER_ONBOARDING_VIEWED = 'USER_ONBOARDING_VIEWED'

/* Data */
export const DATA_EVENT = 'DATA_EVENT'
export const DATA_CATEGORY = 'DATA_CATEGORY'
export const DATA_PLACE = 'DATA_PLACE'
export const DATA_ENTITY = 'DATA_ENTITY'
export const DATA_CONFIG = 'DATA_CONFIG'

/* Modal */
export const MODAL_EVENT_VIEW = 'MODAL_EVENT_VIEW'

/* View */
export const VIEW_SET_VIEW_MODE = 'VIEW_SET_VIEW_MODE'

/* Favorites */
export const USER_ADD_TO_FAVS = 'USER_ADD_TO_FAVS'
export const USER_DEL_TO_FAVS = 'USER_DEL_TO_FAVS'
export const USER_ADD_FAVS = 'USER_ADD_FAVS'
