/* Navigation */
export const NAVIGATION_PUSH = 'NAVIGATION/PUSH'
export const NAVIGATION_REPLACE = 'NAVIGATION/REPLACE'
export const NAVIGATION_GO_BACK = 'NAVIGATION/GO_BACK'
export const NAVIGATION_LOCATION_CHANGE = 'NAVIGATION/LOCATION_CHANGE'
/* User */
export const USER_ONBOARDING_VIEWED = 'USER_ONBOARDING_VIEWED'

/* Feed */

/* Modals */
export const MODAL_EVENT = 'MODAL_EVENT'

