export { default as Main } from './Main'
export { default as OnBoarding } from './OnBoarding'
export { default as Feed } from './Feed'
export { default as Places } from './Places'
export { default as Map } from './Map'
